
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef CO_VEHICLESBC_H
#define CO_VEHICLESBC_H

#include "canfestival/data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 CO_VehicleSBC_valueRangeTest (UNS8 typeValue, void * value);
const indextable * CO_VehicleSBC_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data CO_VehicleSBC_Data;
extern UNS16 MasterHeartbeat;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS8 MotorCommandedStatus;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS8 MotorCurrentPosition;		/* Mapped at index 0x2002, subindex 0x00*/
extern UNS8 MotorCommandPosition;		/* Mapped at index 0x2003, subindex 0x00*/
extern UNS8 MotorCommandSpeed;		/* Mapped at index 0x2004, subindex 0x00*/
extern UNS8 BatteryPackAConnected;		/* Mapped at index 0x2005, subindex 0x00*/
extern UNS8 BatteryPackBConnected;		/* Mapped at index 0x2006, subindex 0x00*/
extern INTEGER32 BatteryPacksTotalCurrent;		/* Mapped at index 0x2007, subindex 0x00*/
extern UNS16 BatteryPackACell1;		/* Mapped at index 0x2008, subindex 0x00*/
extern UNS16 BatteryPackACell2;		/* Mapped at index 0x2009, subindex 0x00*/
extern UNS16 BatteryPackACell3;		/* Mapped at index 0x200A, subindex 0x00*/
extern UNS16 BatteryPackACell4;		/* Mapped at index 0x200B, subindex 0x00*/
extern UNS16 BatteryPackACell5;		/* Mapped at index 0x200C, subindex 0x00*/
extern UNS16 BatteryPackACell6;		/* Mapped at index 0x200D, subindex 0x00*/
extern UNS16 BatteryPackACell7;		/* Mapped at index 0x200E, subindex 0x00*/
extern UNS16 BatteryPackACell8;		/* Mapped at index 0x200F, subindex 0x00*/
extern UNS16 BatteryPackACell9;		/* Mapped at index 0x2010, subindex 0x00*/
extern UNS16 BatteryPackACell10;		/* Mapped at index 0x2011, subindex 0x00*/
extern UNS16 BatteryPackBCell1;		/* Mapped at index 0x2012, subindex 0x00*/
extern UNS16 BatteryPackBCell2;		/* Mapped at index 0x2013, subindex 0x00*/
extern UNS16 BatteryPackBCell3;		/* Mapped at index 0x2014, subindex 0x00*/
extern UNS16 BatteryPackBCell4;		/* Mapped at index 0x2015, subindex 0x00*/
extern UNS16 BatteryPackBCell5;		/* Mapped at index 0x2016, subindex 0x00*/
extern UNS16 BatteryPackBCell6;		/* Mapped at index 0x2017, subindex 0x00*/
extern UNS16 BatteryPackBCell7;		/* Mapped at index 0x2018, subindex 0x00*/
extern UNS16 BatteryPackBCell8;		/* Mapped at index 0x2019, subindex 0x00*/
extern UNS16 BatteryPackBCell9;		/* Mapped at index 0x201A, subindex 0x00*/
extern UNS16 BatteryPackBCell10;		/* Mapped at index 0x201B, subindex 0x00*/
extern UNS8 BatteryCell1Thermocouple;		/* Mapped at index 0x201C, subindex 0x00*/
extern UNS8 BatteryCell2Thermocouple;		/* Mapped at index 0x201D, subindex 0x00*/
extern UNS8 BatteryCell3Thermocouple;		/* Mapped at index 0x201E, subindex 0x00*/
extern UNS8 BatteryCell4Thermocouple;		/* Mapped at index 0x201F, subindex 0x00*/
extern UNS8 BatteryCell5Thermocouple;		/* Mapped at index 0x2020, subindex 0x00*/
extern UNS8 BatteryCell6Thermocouple;		/* Mapped at index 0x2021, subindex 0x00*/
extern UNS8 BatteryCell7Thermocouple;		/* Mapped at index 0x2022, subindex 0x00*/
extern UNS8 BatteryCell8Thermocouple;		/* Mapped at index 0x2023, subindex 0x00*/
extern UNS8 LeakDetected;		/* Mapped at index 0x2024, subindex 0x00*/
extern UNS8 SystemThermocouple1;		/* Mapped at index 0x2025, subindex 0x00*/
extern UNS8 SystemThermocouple2;		/* Mapped at index 0x2026, subindex 0x00*/
extern UNS8 SBCCommsLoss;		/* Mapped at index 0x2027, subindex 0x00*/
extern UNS16 SoftwareMajorVersion;		/* Mapped at index 0x2028, subindex 0x00*/
extern UNS16 SoftwareMinorVersion;		/* Mapped at index 0x2029, subindex 0x00*/
extern UNS16 SoftwareMicroVersion;		/* Mapped at index 0x202A, subindex 0x00*/
extern UNS16 SoftwareBuildVersion;		/* Mapped at index 0x202B, subindex 0x00*/
extern UNS16 PowerInterfaceBoardHeartbeat;		/* Mapped at index 0x202C, subindex 0x00*/
extern UNS8 MotorCalibrationStatus;		/* Mapped at index 0x202D, subindex 0x00*/

#endif // CO_VEHICLESBC_H
