
/* File generated by gen_cfile.py. Should not be modified. */

#include "CO_VehicleSBC.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS16 MasterHeartbeat = 0x0;		/* Mapped at index 0x2000, subindex 0x00 */
UNS8 MotorCommandedStatus = 0x0;		/* Mapped at index 0x2001, subindex 0x00 */
UNS8 MotorCurrentPosition = 0x0;		/* Mapped at index 0x2002, subindex 0x00 */
UNS8 MotorCommandPosition = 0x0;		/* Mapped at index 0x2003, subindex 0x00 */
UNS8 MotorCommandSpeed = 0x0;		/* Mapped at index 0x2004, subindex 0x00 */
UNS8 BatteryPackAConnected = 0x0;		/* Mapped at index 0x2005, subindex 0x00 */
UNS8 BatteryPackBConnected = 0x0;		/* Mapped at index 0x2006, subindex 0x00 */
INTEGER32 BatteryPacksTotalCurrent = 0x0;		/* Mapped at index 0x2007, subindex 0x00 */
UNS16 BatteryPackACell1 = 0x0;		/* Mapped at index 0x2008, subindex 0x00 */
UNS16 BatteryPackACell2 = 0x0;		/* Mapped at index 0x2009, subindex 0x00 */
UNS16 BatteryPackACell3 = 0x0;		/* Mapped at index 0x200A, subindex 0x00 */
UNS16 BatteryPackACell4 = 0x0;		/* Mapped at index 0x200B, subindex 0x00 */
UNS16 BatteryPackACell5 = 0x0;		/* Mapped at index 0x200C, subindex 0x00 */
UNS16 BatteryPackACell6 = 0x0;		/* Mapped at index 0x200D, subindex 0x00 */
UNS16 BatteryPackACell7 = 0x0;		/* Mapped at index 0x200E, subindex 0x00 */
UNS16 BatteryPackACell8 = 0x0;		/* Mapped at index 0x200F, subindex 0x00 */
UNS16 BatteryPackACell9 = 0x0;		/* Mapped at index 0x2010, subindex 0x00 */
UNS16 BatteryPackACell10 = 0x0;		/* Mapped at index 0x2011, subindex 0x00 */
UNS16 BatteryPackBCell1 = 0x0;		/* Mapped at index 0x2012, subindex 0x00 */
UNS16 BatteryPackBCell2 = 0x0;		/* Mapped at index 0x2013, subindex 0x00 */
UNS16 BatteryPackBCell3 = 0x0;		/* Mapped at index 0x2014, subindex 0x00 */
UNS16 BatteryPackBCell4 = 0x0;		/* Mapped at index 0x2015, subindex 0x00 */
UNS16 BatteryPackBCell5 = 0x0;		/* Mapped at index 0x2016, subindex 0x00 */
UNS16 BatteryPackBCell6 = 0x0;		/* Mapped at index 0x2017, subindex 0x00 */
UNS16 BatteryPackBCell7 = 0x0;		/* Mapped at index 0x2018, subindex 0x00 */
UNS16 BatteryPackBCell8 = 0x0;		/* Mapped at index 0x2019, subindex 0x00 */
UNS16 BatteryPackBCell9 = 0x0;		/* Mapped at index 0x201A, subindex 0x00 */
UNS16 BatteryPackBCell10 = 0x0;		/* Mapped at index 0x201B, subindex 0x00 */
UNS8 BatteryCell1Thermocouple = 0x0;		/* Mapped at index 0x201C, subindex 0x00 */
UNS8 BatteryCell2Thermocouple = 0x0;		/* Mapped at index 0x201D, subindex 0x00 */
UNS8 BatteryCell3Thermocouple = 0x0;		/* Mapped at index 0x201E, subindex 0x00 */
UNS8 BatteryCell4Thermocouple = 0x0;		/* Mapped at index 0x201F, subindex 0x00 */
UNS8 BatteryCell5Thermocouple = 0x0;		/* Mapped at index 0x2020, subindex 0x00 */
UNS8 BatteryCell6Thermocouple = 0x0;		/* Mapped at index 0x2021, subindex 0x00 */
UNS8 BatteryCell7Thermocouple = 0x0;		/* Mapped at index 0x2022, subindex 0x00 */
UNS8 BatteryCell8Thermocouple = 0x0;		/* Mapped at index 0x2023, subindex 0x00 */
UNS8 LeakDetected = 0x0;		/* Mapped at index 0x2024, subindex 0x00 */
UNS8 SystemThermocouple1 = 0x0;		/* Mapped at index 0x2025, subindex 0x00 */
UNS8 SystemThermocouple2 = 0x0;		/* Mapped at index 0x2026, subindex 0x00 */
UNS8 SBCCommsLoss = 0x0;		/* Mapped at index 0x2027, subindex 0x00 */
UNS16 SoftwareMajorVersion = 0x0;		/* Mapped at index 0x2028, subindex 0x00 */
UNS16 SoftwareMinorVersion = 0x0;		/* Mapped at index 0x2029, subindex 0x00 */
UNS16 SoftwareMicroVersion = 0x0;		/* Mapped at index 0x202A, subindex 0x00 */
UNS16 SoftwareBuildVersion = 0x0;		/* Mapped at index 0x202B, subindex 0x00 */
UNS16 PowerInterfaceBoardHeartbeat = 0x0;		/* Mapped at index 0x202C, subindex 0x00 */
UNS8 MotorCalibrationStatus = 0x0;		/* Mapped at index 0x202D, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 CO_VehicleSBC_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 CO_VehicleSBC_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 CO_VehicleSBC_iam_a_slave = 0;

TIMER_HANDLE CO_VehicleSBC_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 CO_VehicleSBC_obj1000 = 0x0;	/* 0 */
                    subindex CO_VehicleSBC_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1000, NULL }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 CO_VehicleSBC_obj1001 = 0x0;	/* 0 */
                    subindex CO_VehicleSBC_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1001, NULL }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex CO_VehicleSBC_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1003, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1003[0], NULL }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 CO_VehicleSBC_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 CO_VehicleSBC_obj1006 = 0x0;   /* 0 */

/* index 0x100C :   Guard Time */ 
                    UNS16 CO_VehicleSBC_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 CO_VehicleSBC_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 CO_VehicleSBC_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1016 = 0;
                    UNS32 CO_VehicleSBC_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 CO_VehicleSBC_obj1017 = 0x3E8;	/* 1000 */
                    subindex CO_VehicleSBC_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1017, NULL }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 CO_VehicleSBC_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 CO_VehicleSBC_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 CO_VehicleSBC_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex CO_VehicleSBC_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1018, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1018_Vendor_ID, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1018_Product_Code, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1018_Revision_Number, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1018_Serial_Number, NULL }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x607;	/* 1543 */
                    UNS32 CO_VehicleSBC_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x587;	/* 1415 */
                    UNS8 CO_VehicleSBC_obj1280_Node_ID_of_the_SDO_Server = 0x7;	/* 7 */
                    subindex CO_VehicleSBC_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1280, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1280_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1280_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1280_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1281 :   Client SDO 2 Parameter. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1281 = 3; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1281_COB_ID_Client_to_Server_Transmit_SDO = 0x608;	/* 1544 */
                    UNS32 CO_VehicleSBC_obj1281_COB_ID_Server_to_Client_Receive_SDO = 0x588;	/* 1416 */
                    UNS8 CO_VehicleSBC_obj1281_Node_ID_of_the_SDO_Server = 0x8;	/* 8 */
                    subindex CO_VehicleSBC_Index1281[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1281, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1281_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1281_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1281_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1400_COB_ID_used_by_PDO = 0x2B5;	/* 693 */
                    UNS8 CO_VehicleSBC_obj1400_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 CO_VehicleSBC_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex CO_VehicleSBC_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1400, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1400_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1400_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1400_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1400_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1400_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1400_SYNC_start_value, NULL }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1401_COB_ID_used_by_PDO = 0x195;	/* 405 */
                    UNS8 CO_VehicleSBC_obj1401_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 CO_VehicleSBC_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex CO_VehicleSBC_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1401, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1401_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1401_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1401_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1401_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1401_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1401_SYNC_start_value, NULL }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1402_COB_ID_used_by_PDO = 0x1B5;	/* 437 */
                    UNS8 CO_VehicleSBC_obj1402_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 CO_VehicleSBC_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex CO_VehicleSBC_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1402, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1402_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1402_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1402_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1402_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1402_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1402_SYNC_start_value, NULL }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1403_COB_ID_used_by_PDO = 0x1D5;	/* 469 */
                    UNS8 CO_VehicleSBC_obj1403_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 CO_VehicleSBC_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex CO_VehicleSBC_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1403, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1403_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1403_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1403_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1403_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1403_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1403_SYNC_start_value, NULL }
                     };

/* index 0x1404 :   Receive PDO 5 Parameter. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1404 = 6; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1404_COB_ID_used_by_PDO = 0x1F5;	/* 501 */
                    UNS8 CO_VehicleSBC_obj1404_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 CO_VehicleSBC_obj1404_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1404_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj1404_Event_Timer = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1404_SYNC_start_value = 0x0;	/* 0 */
                    subindex CO_VehicleSBC_Index1404[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1404, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1404_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1404_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1404_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1404_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1404_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1404_SYNC_start_value, NULL }
                     };

/* index 0x1405 :   Receive PDO 6 Parameter. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1405 = 6; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1405_COB_ID_used_by_PDO = 0x215;	/* 533 */
                    UNS8 CO_VehicleSBC_obj1405_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 CO_VehicleSBC_obj1405_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1405_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj1405_Event_Timer = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1405_SYNC_start_value = 0x0;	/* 0 */
                    subindex CO_VehicleSBC_Index1405[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1405, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1405_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1405_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1405_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1405_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1405_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1405_SYNC_start_value, NULL }
                     };

/* index 0x1406 :   Receive PDO 7 Parameter. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1406 = 6; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1406_COB_ID_used_by_PDO = 0x235;	/* 565 */
                    UNS8 CO_VehicleSBC_obj1406_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 CO_VehicleSBC_obj1406_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1406_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj1406_Event_Timer = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1406_SYNC_start_value = 0x0;	/* 0 */
                    subindex CO_VehicleSBC_Index1406[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1406, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1406_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1406_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1406_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1406_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1406_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1406_SYNC_start_value, NULL }
                     };

/* index 0x1407 :   Receive PDO 8 Parameter. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1407 = 6; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1407_COB_ID_used_by_PDO = 0x255;	/* 597 */
                    UNS8 CO_VehicleSBC_obj1407_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 CO_VehicleSBC_obj1407_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1407_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj1407_Event_Timer = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1407_SYNC_start_value = 0x0;	/* 0 */
                    subindex CO_VehicleSBC_Index1407[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1407, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1407_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1407_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1407_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1407_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1407_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1407_SYNC_start_value, NULL }
                     };

/* index 0x1408 :   Receive PDO 9 Parameter. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1408 = 6; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1408_COB_ID_used_by_PDO = 0x275;	/* 629 */
                    UNS8 CO_VehicleSBC_obj1408_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 CO_VehicleSBC_obj1408_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1408_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj1408_Event_Timer = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1408_SYNC_start_value = 0x0;	/* 0 */
                    subindex CO_VehicleSBC_Index1408[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1408, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1408_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1408_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1408_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1408_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1408_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1408_SYNC_start_value, NULL }
                     };

/* index 0x1409 :   Receive PDO 10 Parameter. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1409 = 6; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1409_COB_ID_used_by_PDO = 0x295;	/* 661 */
                    UNS8 CO_VehicleSBC_obj1409_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 CO_VehicleSBC_obj1409_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1409_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj1409_Event_Timer = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1409_SYNC_start_value = 0x0;	/* 0 */
                    subindex CO_VehicleSBC_Index1409[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1409, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1409_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1409_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1409_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1409_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1409_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1409_SYNC_start_value, NULL }
                     };

/* index 0x140A :   Receive PDO 11 Parameter. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj140A = 6; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj140A_COB_ID_used_by_PDO = 0x345;	/* 837 */
                    UNS8 CO_VehicleSBC_obj140A_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 CO_VehicleSBC_obj140A_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj140A_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj140A_Event_Timer = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj140A_SYNC_start_value = 0x0;	/* 0 */
                    subindex CO_VehicleSBC_Index140A[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj140A, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj140A_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj140A_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj140A_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj140A_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj140A_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj140A_SYNC_start_value, NULL }
                     };

/* index 0x140B :   Receive PDO 12 Parameter. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj140B = 6; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj140B_COB_ID_used_by_PDO = 0x465;	/* 1125 */
                    UNS8 CO_VehicleSBC_obj140B_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 CO_VehicleSBC_obj140B_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj140B_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj140B_Event_Timer = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj140B_SYNC_start_value = 0x0;	/* 0 */
                    subindex CO_VehicleSBC_Index140B[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj140B, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj140B_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj140B_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj140B_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj140B_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj140B_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj140B_SYNC_start_value, NULL }
                     };

/* index 0x140C :   Receive PDO 13 Parameter. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj140C = 6; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj140C_COB_ID_used_by_PDO = 0x485;	/* 1157 */
                    UNS8 CO_VehicleSBC_obj140C_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 CO_VehicleSBC_obj140C_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj140C_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj140C_Event_Timer = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj140C_SYNC_start_value = 0x0;	/* 0 */
                    subindex CO_VehicleSBC_Index140C[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj140C, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj140C_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj140C_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj140C_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj140C_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj140C_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj140C_SYNC_start_value, NULL }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1600 = 3; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1600[] = 
                    {
                      0x20010008,	/* 536936456 */
                      0x20020008,	/* 537001992 */
                      0x202D0008	/* 539820040 */
                    };
                    subindex CO_VehicleSBC_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1600, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1600[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1600[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1600[2], NULL }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1601 = 3; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1601[] = 
                    {
                      0x20050001,	/* 537198593 */
                      0x20060001,	/* 537264129 */
                      0x20070020	/* 537329696 */
                    };
                    subindex CO_VehicleSBC_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1601, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1601[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1601[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1601[2], NULL }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1602 = 4; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1602[] = 
                    {
                      0x20080010,	/* 537395216 */
                      0x20090010,	/* 537460752 */
                      0x200A0010,	/* 537526288 */
                      0x200B0010	/* 537591824 */
                    };
                    subindex CO_VehicleSBC_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1602, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1602[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1602[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1602[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1602[3], NULL }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1603 = 4; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1603[] = 
                    {
                      0x200C0010,	/* 537657360 */
                      0x200D0010,	/* 537722896 */
                      0x200E0010,	/* 537788432 */
                      0x200F0010	/* 537853968 */
                    };
                    subindex CO_VehicleSBC_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1603, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1603[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1603[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1603[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1603[3], NULL }
                     };

/* index 0x1604 :   Receive PDO 5 Mapping. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1604 = 2; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1604[] = 
                    {
                      0x20100010,	/* 537919504 */
                      0x20110010	/* 537985040 */
                    };
                    subindex CO_VehicleSBC_Index1604[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1604, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1604[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1604[1], NULL }
                     };

/* index 0x1605 :   Receive PDO 6 Mapping. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1605 = 4; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1605[] = 
                    {
                      0x20120010,	/* 538050576 */
                      0x20130010,	/* 538116112 */
                      0x20140010,	/* 538181648 */
                      0x20150010	/* 538247184 */
                    };
                    subindex CO_VehicleSBC_Index1605[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1605, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1605[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1605[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1605[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1605[3], NULL }
                     };

/* index 0x1606 :   Receive PDO 7 Mapping. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1606 = 4; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1606[] = 
                    {
                      0x20160010,	/* 538312720 */
                      0x20170010,	/* 538378256 */
                      0x20180010,	/* 538443792 */
                      0x20190010	/* 538509328 */
                    };
                    subindex CO_VehicleSBC_Index1606[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1606, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1606[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1606[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1606[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1606[3], NULL }
                     };

/* index 0x1607 :   Receive PDO 8 Mapping. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1607 = 2; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1607[] = 
                    {
                      0x201A0010,	/* 538574864 */
                      0x201B0010	/* 538640400 */
                    };
                    subindex CO_VehicleSBC_Index1607[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1607, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1607[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1607[1], NULL }
                     };

/* index 0x1608 :   Receive PDO 9 Mapping. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1608 = 8; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1608[] = 
                    {
                      0x201C0008,	/* 538705928 */
                      0x201D0008,	/* 538771464 */
                      0x201E0008,	/* 538837000 */
                      0x201F0008,	/* 538902536 */
                      0x20200008,	/* 538968072 */
                      0x20210008,	/* 539033608 */
                      0x20220008,	/* 539099144 */
                      0x20230008	/* 539164680 */
                    };
                    subindex CO_VehicleSBC_Index1608[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1608, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1608[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1608[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1608[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1608[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1608[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1608[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1608[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1608[7], NULL }
                     };

/* index 0x1609 :   Receive PDO 10 Mapping. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1609 = 2; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1609[] = 
                    {
                      0x20240001,	/* 539230209 */
                      0x20250008	/* 539295752 */
                    };
                    subindex CO_VehicleSBC_Index1609[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1609, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1609[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1609[1], NULL }
                     };

/* index 0x160A :   Receive PDO 11 Mapping. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj160A = 1; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj160A[] = 
                    {
                      0x20270001	/* 539426817 */
                    };
                    subindex CO_VehicleSBC_Index160A[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj160A, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj160A[0], NULL }
                     };

/* index 0x160B :   Receive PDO 12 Mapping. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj160B = 4; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj160B[] = 
                    {
                      0x20280010,	/* 539492368 */
                      0x20290010,	/* 539557904 */
                      0x202A0010,	/* 539623440 */
                      0x202B0010	/* 539688976 */
                    };
                    subindex CO_VehicleSBC_Index160B[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj160B, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj160B[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj160B[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj160B[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj160B[3], NULL }
                     };

/* index 0x160C :   Receive PDO 13 Mapping. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj160C = 1; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj160C[] = 
                    {
                      0x202C0010	/* 539754512 */
                    };
                    subindex CO_VehicleSBC_Index160C[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj160C, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj160C[0], NULL }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1800 = 5; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1800_COB_ID_used_by_PDO = 0x187;	/* 391 */
                    UNS8 CO_VehicleSBC_obj1800_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 CO_VehicleSBC_obj1800_Inhibit_Time = 0x64;	/* 100 */
                    UNS8 CO_VehicleSBC_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj1800_Event_Timer = 0xA;	/* 10 */
                    subindex CO_VehicleSBC_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1800, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1800_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1800_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1800_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1800_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1800_Event_Timer, NULL }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1801_COB_ID_used_by_PDO = 0x2A5;	/* 677 */
                    UNS8 CO_VehicleSBC_obj1801_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 CO_VehicleSBC_obj1801_Inhibit_Time = 0x64;	/* 100 */
                    UNS8 CO_VehicleSBC_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj1801_Event_Timer = 0xA;	/* 10 */
                    UNS8 CO_VehicleSBC_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    subindex CO_VehicleSBC_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1801, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1801_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1801_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1801_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1801_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1801_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1801_SYNC_start_value, NULL }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1A00 = 1; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1A00[] = 
                    {
                      0x20000010	/* 536870928 */
                    };
                    subindex CO_VehicleSBC_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1A00, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1A00[0], NULL }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1A01 = 2; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1A01[] = 
                    {
                      0x20030008,	/* 537067528 */
                      0x20040008	/* 537133064 */
                    };
                    subindex CO_VehicleSBC_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1A01, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1A01[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1A01[1], NULL }
                     };

/* index 0x2000 :   Mapped variable MasterHeartbeat */
                    subindex CO_VehicleSBC_Index2000[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&MasterHeartbeat, NULL }
                     };

/* index 0x2001 :   Mapped variable MotorCommandedStatus */
                    subindex CO_VehicleSBC_Index2001[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MotorCommandedStatus, NULL }
                     };

/* index 0x2002 :   Mapped variable MotorCurrentPosition */
                    subindex CO_VehicleSBC_Index2002[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MotorCurrentPosition, NULL }
                     };

/* index 0x2003 :   Mapped variable MotorCommandPosition */
                    subindex CO_VehicleSBC_Index2003[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MotorCommandPosition, NULL }
                     };

/* index 0x2004 :   Mapped variable MotorCommandSpeed */
                    subindex CO_VehicleSBC_Index2004[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MotorCommandSpeed, NULL }
                     };

/* index 0x2005 :   Mapped variable BatteryPackAConnected */
                    subindex CO_VehicleSBC_Index2005[] = 
                     {
                       { RW, boolean, sizeof (UNS8), (void*)&BatteryPackAConnected, NULL }
                     };

/* index 0x2006 :   Mapped variable BatteryPackBConnected */
                    subindex CO_VehicleSBC_Index2006[] = 
                     {
                       { RW, boolean, sizeof (UNS8), (void*)&BatteryPackBConnected, NULL }
                     };

/* index 0x2007 :   Mapped variable BatteryPacksTotalCurrent */
                    subindex CO_VehicleSBC_Index2007[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&BatteryPacksTotalCurrent, NULL }
                     };

/* index 0x2008 :   Mapped variable BatteryPackACell1 */
                    subindex CO_VehicleSBC_Index2008[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&BatteryPackACell1, NULL }
                     };

/* index 0x2009 :   Mapped variable BatteryPackACell2 */
                    subindex CO_VehicleSBC_Index2009[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&BatteryPackACell2, NULL }
                     };

/* index 0x200A :   Mapped variable BatteryPackACell3 */
                    subindex CO_VehicleSBC_Index200A[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&BatteryPackACell3, NULL }
                     };

/* index 0x200B :   Mapped variable BatteryPackACell4 */
                    subindex CO_VehicleSBC_Index200B[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&BatteryPackACell4, NULL }
                     };

/* index 0x200C :   Mapped variable BatteryPackACell5 */
                    subindex CO_VehicleSBC_Index200C[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&BatteryPackACell5, NULL }
                     };

/* index 0x200D :   Mapped variable BatteryPackACell6 */
                    subindex CO_VehicleSBC_Index200D[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&BatteryPackACell6, NULL }
                     };

/* index 0x200E :   Mapped variable BatteryPackACell7 */
                    subindex CO_VehicleSBC_Index200E[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&BatteryPackACell7, NULL }
                     };

/* index 0x200F :   Mapped variable BatteryPackACell8 */
                    subindex CO_VehicleSBC_Index200F[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&BatteryPackACell8, NULL }
                     };

/* index 0x2010 :   Mapped variable BatteryPackACell9 */
                    subindex CO_VehicleSBC_Index2010[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&BatteryPackACell9, NULL }
                     };

/* index 0x2011 :   Mapped variable BatteryPackACell10 */
                    subindex CO_VehicleSBC_Index2011[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&BatteryPackACell10, NULL }
                     };

/* index 0x2012 :   Mapped variable BatteryPackBCell1 */
                    subindex CO_VehicleSBC_Index2012[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&BatteryPackBCell1, NULL }
                     };

/* index 0x2013 :   Mapped variable BatteryPackBCell2 */
                    subindex CO_VehicleSBC_Index2013[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&BatteryPackBCell2, NULL }
                     };

/* index 0x2014 :   Mapped variable BatteryPackBCell3 */
                    subindex CO_VehicleSBC_Index2014[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&BatteryPackBCell3, NULL }
                     };

/* index 0x2015 :   Mapped variable BatteryPackBCell4 */
                    subindex CO_VehicleSBC_Index2015[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&BatteryPackBCell4, NULL }
                     };

/* index 0x2016 :   Mapped variable BatteryPackBCell5 */
                    subindex CO_VehicleSBC_Index2016[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&BatteryPackBCell5, NULL }
                     };

/* index 0x2017 :   Mapped variable BatteryPackBCell6 */
                    subindex CO_VehicleSBC_Index2017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&BatteryPackBCell6, NULL }
                     };

/* index 0x2018 :   Mapped variable BatteryPackBCell7 */
                    subindex CO_VehicleSBC_Index2018[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&BatteryPackBCell7, NULL }
                     };

/* index 0x2019 :   Mapped variable BatteryPackBCell8 */
                    subindex CO_VehicleSBC_Index2019[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&BatteryPackBCell8, NULL }
                     };

/* index 0x201A :   Mapped variable BatteryPackBCell9 */
                    subindex CO_VehicleSBC_Index201A[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&BatteryPackBCell9, NULL }
                     };

/* index 0x201B :   Mapped variable BatteryPackBCell10 */
                    subindex CO_VehicleSBC_Index201B[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&BatteryPackBCell10, NULL }
                     };

/* index 0x201C :   Mapped variable BatteryCell1Thermocouple */
                    subindex CO_VehicleSBC_Index201C[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&BatteryCell1Thermocouple, NULL }
                     };

/* index 0x201D :   Mapped variable BatteryCell2Thermocouple */
                    subindex CO_VehicleSBC_Index201D[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&BatteryCell2Thermocouple, NULL }
                     };

/* index 0x201E :   Mapped variable BatteryCell3Thermocouple */
                    subindex CO_VehicleSBC_Index201E[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&BatteryCell3Thermocouple, NULL }
                     };

/* index 0x201F :   Mapped variable BatteryCell4Thermocouple */
                    subindex CO_VehicleSBC_Index201F[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&BatteryCell4Thermocouple, NULL }
                     };

/* index 0x2020 :   Mapped variable BatteryCell5Thermocouple */
                    subindex CO_VehicleSBC_Index2020[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&BatteryCell5Thermocouple, NULL }
                     };

/* index 0x2021 :   Mapped variable BatteryCell6Thermocouple */
                    subindex CO_VehicleSBC_Index2021[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&BatteryCell6Thermocouple, NULL }
                     };

/* index 0x2022 :   Mapped variable BatteryCell7Thermocouple */
                    subindex CO_VehicleSBC_Index2022[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&BatteryCell7Thermocouple, NULL }
                     };

/* index 0x2023 :   Mapped variable BatteryCell8Thermocouple */
                    subindex CO_VehicleSBC_Index2023[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&BatteryCell8Thermocouple, NULL }
                     };

/* index 0x2024 :   Mapped variable LeakDetected */
                    subindex CO_VehicleSBC_Index2024[] = 
                     {
                       { RW, boolean, sizeof (UNS8), (void*)&LeakDetected, NULL }
                     };

/* index 0x2025 :   Mapped variable SystemThermocouple1 */
                    subindex CO_VehicleSBC_Index2025[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&SystemThermocouple1, NULL }
                     };

/* index 0x2026 :   Mapped variable SystemThermocouple2 */
                    subindex CO_VehicleSBC_Index2026[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&SystemThermocouple2, NULL }
                     };

/* index 0x2027 :   Mapped variable SBCCommsLoss */
                    subindex CO_VehicleSBC_Index2027[] = 
                     {
                       { RW, boolean, sizeof (UNS8), (void*)&SBCCommsLoss, NULL }
                     };

/* index 0x2028 :   Mapped variable SoftwareMajorVersion */
                    subindex CO_VehicleSBC_Index2028[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&SoftwareMajorVersion, NULL }
                     };

/* index 0x2029 :   Mapped variable SoftwareMinorVersion */
                    subindex CO_VehicleSBC_Index2029[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&SoftwareMinorVersion, NULL }
                     };

/* index 0x202A :   Mapped variable SoftwareMicroVersion */
                    subindex CO_VehicleSBC_Index202A[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&SoftwareMicroVersion, NULL }
                     };

/* index 0x202B :   Mapped variable SoftwareBuildVersion */
                    subindex CO_VehicleSBC_Index202B[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&SoftwareBuildVersion, NULL }
                     };

/* index 0x202C :   Mapped variable PowerInterfaceBoardHeartbeat */
                    subindex CO_VehicleSBC_Index202C[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&PowerInterfaceBoardHeartbeat, NULL }
                     };

/* index 0x202D :   Mapped variable MotorCalibrationStatus */
                    subindex CO_VehicleSBC_Index202D[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MotorCalibrationStatus, NULL }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable CO_VehicleSBC_objdict[] = 
{
  { (subindex*)CO_VehicleSBC_Index1000,sizeof(CO_VehicleSBC_Index1000)/sizeof(CO_VehicleSBC_Index1000[0]), 0x1000},
  { (subindex*)CO_VehicleSBC_Index1001,sizeof(CO_VehicleSBC_Index1001)/sizeof(CO_VehicleSBC_Index1001[0]), 0x1001},
  { (subindex*)CO_VehicleSBC_Index1017,sizeof(CO_VehicleSBC_Index1017)/sizeof(CO_VehicleSBC_Index1017[0]), 0x1017},
  { (subindex*)CO_VehicleSBC_Index1018,sizeof(CO_VehicleSBC_Index1018)/sizeof(CO_VehicleSBC_Index1018[0]), 0x1018},
  { (subindex*)CO_VehicleSBC_Index1280,sizeof(CO_VehicleSBC_Index1280)/sizeof(CO_VehicleSBC_Index1280[0]), 0x1280},
  { (subindex*)CO_VehicleSBC_Index1281,sizeof(CO_VehicleSBC_Index1281)/sizeof(CO_VehicleSBC_Index1281[0]), 0x1281},
  { (subindex*)CO_VehicleSBC_Index1400,sizeof(CO_VehicleSBC_Index1400)/sizeof(CO_VehicleSBC_Index1400[0]), 0x1400},
  { (subindex*)CO_VehicleSBC_Index1401,sizeof(CO_VehicleSBC_Index1401)/sizeof(CO_VehicleSBC_Index1401[0]), 0x1401},
  { (subindex*)CO_VehicleSBC_Index1402,sizeof(CO_VehicleSBC_Index1402)/sizeof(CO_VehicleSBC_Index1402[0]), 0x1402},
  { (subindex*)CO_VehicleSBC_Index1403,sizeof(CO_VehicleSBC_Index1403)/sizeof(CO_VehicleSBC_Index1403[0]), 0x1403},
  { (subindex*)CO_VehicleSBC_Index1404,sizeof(CO_VehicleSBC_Index1404)/sizeof(CO_VehicleSBC_Index1404[0]), 0x1404},
  { (subindex*)CO_VehicleSBC_Index1405,sizeof(CO_VehicleSBC_Index1405)/sizeof(CO_VehicleSBC_Index1405[0]), 0x1405},
  { (subindex*)CO_VehicleSBC_Index1406,sizeof(CO_VehicleSBC_Index1406)/sizeof(CO_VehicleSBC_Index1406[0]), 0x1406},
  { (subindex*)CO_VehicleSBC_Index1407,sizeof(CO_VehicleSBC_Index1407)/sizeof(CO_VehicleSBC_Index1407[0]), 0x1407},
  { (subindex*)CO_VehicleSBC_Index1408,sizeof(CO_VehicleSBC_Index1408)/sizeof(CO_VehicleSBC_Index1408[0]), 0x1408},
  { (subindex*)CO_VehicleSBC_Index1409,sizeof(CO_VehicleSBC_Index1409)/sizeof(CO_VehicleSBC_Index1409[0]), 0x1409},
  { (subindex*)CO_VehicleSBC_Index140A,sizeof(CO_VehicleSBC_Index140A)/sizeof(CO_VehicleSBC_Index140A[0]), 0x140A},
  { (subindex*)CO_VehicleSBC_Index140B,sizeof(CO_VehicleSBC_Index140B)/sizeof(CO_VehicleSBC_Index140B[0]), 0x140B},
  { (subindex*)CO_VehicleSBC_Index140C,sizeof(CO_VehicleSBC_Index140C)/sizeof(CO_VehicleSBC_Index140C[0]), 0x140C},
  { (subindex*)CO_VehicleSBC_Index1600,sizeof(CO_VehicleSBC_Index1600)/sizeof(CO_VehicleSBC_Index1600[0]), 0x1600},
  { (subindex*)CO_VehicleSBC_Index1601,sizeof(CO_VehicleSBC_Index1601)/sizeof(CO_VehicleSBC_Index1601[0]), 0x1601},
  { (subindex*)CO_VehicleSBC_Index1602,sizeof(CO_VehicleSBC_Index1602)/sizeof(CO_VehicleSBC_Index1602[0]), 0x1602},
  { (subindex*)CO_VehicleSBC_Index1603,sizeof(CO_VehicleSBC_Index1603)/sizeof(CO_VehicleSBC_Index1603[0]), 0x1603},
  { (subindex*)CO_VehicleSBC_Index1604,sizeof(CO_VehicleSBC_Index1604)/sizeof(CO_VehicleSBC_Index1604[0]), 0x1604},
  { (subindex*)CO_VehicleSBC_Index1605,sizeof(CO_VehicleSBC_Index1605)/sizeof(CO_VehicleSBC_Index1605[0]), 0x1605},
  { (subindex*)CO_VehicleSBC_Index1606,sizeof(CO_VehicleSBC_Index1606)/sizeof(CO_VehicleSBC_Index1606[0]), 0x1606},
  { (subindex*)CO_VehicleSBC_Index1607,sizeof(CO_VehicleSBC_Index1607)/sizeof(CO_VehicleSBC_Index1607[0]), 0x1607},
  { (subindex*)CO_VehicleSBC_Index1608,sizeof(CO_VehicleSBC_Index1608)/sizeof(CO_VehicleSBC_Index1608[0]), 0x1608},
  { (subindex*)CO_VehicleSBC_Index1609,sizeof(CO_VehicleSBC_Index1609)/sizeof(CO_VehicleSBC_Index1609[0]), 0x1609},
  { (subindex*)CO_VehicleSBC_Index160A,sizeof(CO_VehicleSBC_Index160A)/sizeof(CO_VehicleSBC_Index160A[0]), 0x160A},
  { (subindex*)CO_VehicleSBC_Index160B,sizeof(CO_VehicleSBC_Index160B)/sizeof(CO_VehicleSBC_Index160B[0]), 0x160B},
  { (subindex*)CO_VehicleSBC_Index160C,sizeof(CO_VehicleSBC_Index160C)/sizeof(CO_VehicleSBC_Index160C[0]), 0x160C},
  { (subindex*)CO_VehicleSBC_Index1800,sizeof(CO_VehicleSBC_Index1800)/sizeof(CO_VehicleSBC_Index1800[0]), 0x1800},
  { (subindex*)CO_VehicleSBC_Index1801,sizeof(CO_VehicleSBC_Index1801)/sizeof(CO_VehicleSBC_Index1801[0]), 0x1801},
  { (subindex*)CO_VehicleSBC_Index1A00,sizeof(CO_VehicleSBC_Index1A00)/sizeof(CO_VehicleSBC_Index1A00[0]), 0x1A00},
  { (subindex*)CO_VehicleSBC_Index1A01,sizeof(CO_VehicleSBC_Index1A01)/sizeof(CO_VehicleSBC_Index1A01[0]), 0x1A01},
  { (subindex*)CO_VehicleSBC_Index2000,sizeof(CO_VehicleSBC_Index2000)/sizeof(CO_VehicleSBC_Index2000[0]), 0x2000},
  { (subindex*)CO_VehicleSBC_Index2001,sizeof(CO_VehicleSBC_Index2001)/sizeof(CO_VehicleSBC_Index2001[0]), 0x2001},
  { (subindex*)CO_VehicleSBC_Index2002,sizeof(CO_VehicleSBC_Index2002)/sizeof(CO_VehicleSBC_Index2002[0]), 0x2002},
  { (subindex*)CO_VehicleSBC_Index2003,sizeof(CO_VehicleSBC_Index2003)/sizeof(CO_VehicleSBC_Index2003[0]), 0x2003},
  { (subindex*)CO_VehicleSBC_Index2004,sizeof(CO_VehicleSBC_Index2004)/sizeof(CO_VehicleSBC_Index2004[0]), 0x2004},
  { (subindex*)CO_VehicleSBC_Index2005,sizeof(CO_VehicleSBC_Index2005)/sizeof(CO_VehicleSBC_Index2005[0]), 0x2005},
  { (subindex*)CO_VehicleSBC_Index2006,sizeof(CO_VehicleSBC_Index2006)/sizeof(CO_VehicleSBC_Index2006[0]), 0x2006},
  { (subindex*)CO_VehicleSBC_Index2007,sizeof(CO_VehicleSBC_Index2007)/sizeof(CO_VehicleSBC_Index2007[0]), 0x2007},
  { (subindex*)CO_VehicleSBC_Index2008,sizeof(CO_VehicleSBC_Index2008)/sizeof(CO_VehicleSBC_Index2008[0]), 0x2008},
  { (subindex*)CO_VehicleSBC_Index2009,sizeof(CO_VehicleSBC_Index2009)/sizeof(CO_VehicleSBC_Index2009[0]), 0x2009},
  { (subindex*)CO_VehicleSBC_Index200A,sizeof(CO_VehicleSBC_Index200A)/sizeof(CO_VehicleSBC_Index200A[0]), 0x200A},
  { (subindex*)CO_VehicleSBC_Index200B,sizeof(CO_VehicleSBC_Index200B)/sizeof(CO_VehicleSBC_Index200B[0]), 0x200B},
  { (subindex*)CO_VehicleSBC_Index200C,sizeof(CO_VehicleSBC_Index200C)/sizeof(CO_VehicleSBC_Index200C[0]), 0x200C},
  { (subindex*)CO_VehicleSBC_Index200D,sizeof(CO_VehicleSBC_Index200D)/sizeof(CO_VehicleSBC_Index200D[0]), 0x200D},
  { (subindex*)CO_VehicleSBC_Index200E,sizeof(CO_VehicleSBC_Index200E)/sizeof(CO_VehicleSBC_Index200E[0]), 0x200E},
  { (subindex*)CO_VehicleSBC_Index200F,sizeof(CO_VehicleSBC_Index200F)/sizeof(CO_VehicleSBC_Index200F[0]), 0x200F},
  { (subindex*)CO_VehicleSBC_Index2010,sizeof(CO_VehicleSBC_Index2010)/sizeof(CO_VehicleSBC_Index2010[0]), 0x2010},
  { (subindex*)CO_VehicleSBC_Index2011,sizeof(CO_VehicleSBC_Index2011)/sizeof(CO_VehicleSBC_Index2011[0]), 0x2011},
  { (subindex*)CO_VehicleSBC_Index2012,sizeof(CO_VehicleSBC_Index2012)/sizeof(CO_VehicleSBC_Index2012[0]), 0x2012},
  { (subindex*)CO_VehicleSBC_Index2013,sizeof(CO_VehicleSBC_Index2013)/sizeof(CO_VehicleSBC_Index2013[0]), 0x2013},
  { (subindex*)CO_VehicleSBC_Index2014,sizeof(CO_VehicleSBC_Index2014)/sizeof(CO_VehicleSBC_Index2014[0]), 0x2014},
  { (subindex*)CO_VehicleSBC_Index2015,sizeof(CO_VehicleSBC_Index2015)/sizeof(CO_VehicleSBC_Index2015[0]), 0x2015},
  { (subindex*)CO_VehicleSBC_Index2016,sizeof(CO_VehicleSBC_Index2016)/sizeof(CO_VehicleSBC_Index2016[0]), 0x2016},
  { (subindex*)CO_VehicleSBC_Index2017,sizeof(CO_VehicleSBC_Index2017)/sizeof(CO_VehicleSBC_Index2017[0]), 0x2017},
  { (subindex*)CO_VehicleSBC_Index2018,sizeof(CO_VehicleSBC_Index2018)/sizeof(CO_VehicleSBC_Index2018[0]), 0x2018},
  { (subindex*)CO_VehicleSBC_Index2019,sizeof(CO_VehicleSBC_Index2019)/sizeof(CO_VehicleSBC_Index2019[0]), 0x2019},
  { (subindex*)CO_VehicleSBC_Index201A,sizeof(CO_VehicleSBC_Index201A)/sizeof(CO_VehicleSBC_Index201A[0]), 0x201A},
  { (subindex*)CO_VehicleSBC_Index201B,sizeof(CO_VehicleSBC_Index201B)/sizeof(CO_VehicleSBC_Index201B[0]), 0x201B},
  { (subindex*)CO_VehicleSBC_Index201C,sizeof(CO_VehicleSBC_Index201C)/sizeof(CO_VehicleSBC_Index201C[0]), 0x201C},
  { (subindex*)CO_VehicleSBC_Index201D,sizeof(CO_VehicleSBC_Index201D)/sizeof(CO_VehicleSBC_Index201D[0]), 0x201D},
  { (subindex*)CO_VehicleSBC_Index201E,sizeof(CO_VehicleSBC_Index201E)/sizeof(CO_VehicleSBC_Index201E[0]), 0x201E},
  { (subindex*)CO_VehicleSBC_Index201F,sizeof(CO_VehicleSBC_Index201F)/sizeof(CO_VehicleSBC_Index201F[0]), 0x201F},
  { (subindex*)CO_VehicleSBC_Index2020,sizeof(CO_VehicleSBC_Index2020)/sizeof(CO_VehicleSBC_Index2020[0]), 0x2020},
  { (subindex*)CO_VehicleSBC_Index2021,sizeof(CO_VehicleSBC_Index2021)/sizeof(CO_VehicleSBC_Index2021[0]), 0x2021},
  { (subindex*)CO_VehicleSBC_Index2022,sizeof(CO_VehicleSBC_Index2022)/sizeof(CO_VehicleSBC_Index2022[0]), 0x2022},
  { (subindex*)CO_VehicleSBC_Index2023,sizeof(CO_VehicleSBC_Index2023)/sizeof(CO_VehicleSBC_Index2023[0]), 0x2023},
  { (subindex*)CO_VehicleSBC_Index2024,sizeof(CO_VehicleSBC_Index2024)/sizeof(CO_VehicleSBC_Index2024[0]), 0x2024},
  { (subindex*)CO_VehicleSBC_Index2025,sizeof(CO_VehicleSBC_Index2025)/sizeof(CO_VehicleSBC_Index2025[0]), 0x2025},
  { (subindex*)CO_VehicleSBC_Index2026,sizeof(CO_VehicleSBC_Index2026)/sizeof(CO_VehicleSBC_Index2026[0]), 0x2026},
  { (subindex*)CO_VehicleSBC_Index2027,sizeof(CO_VehicleSBC_Index2027)/sizeof(CO_VehicleSBC_Index2027[0]), 0x2027},
  { (subindex*)CO_VehicleSBC_Index2028,sizeof(CO_VehicleSBC_Index2028)/sizeof(CO_VehicleSBC_Index2028[0]), 0x2028},
  { (subindex*)CO_VehicleSBC_Index2029,sizeof(CO_VehicleSBC_Index2029)/sizeof(CO_VehicleSBC_Index2029[0]), 0x2029},
  { (subindex*)CO_VehicleSBC_Index202A,sizeof(CO_VehicleSBC_Index202A)/sizeof(CO_VehicleSBC_Index202A[0]), 0x202A},
  { (subindex*)CO_VehicleSBC_Index202B,sizeof(CO_VehicleSBC_Index202B)/sizeof(CO_VehicleSBC_Index202B[0]), 0x202B},
  { (subindex*)CO_VehicleSBC_Index202C,sizeof(CO_VehicleSBC_Index202C)/sizeof(CO_VehicleSBC_Index202C[0]), 0x202C},
  { (subindex*)CO_VehicleSBC_Index202D,sizeof(CO_VehicleSBC_Index202D)/sizeof(CO_VehicleSBC_Index202D[0]), 0x202D},
};

const indextable * CO_VehicleSBC_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode)
{
	int i;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1017: i = 2;break;
		case 0x1018: i = 3;break;
		case 0x1280: i = 4;break;
		case 0x1281: i = 5;break;
		case 0x1400: i = 6;break;
		case 0x1401: i = 7;break;
		case 0x1402: i = 8;break;
		case 0x1403: i = 9;break;
		case 0x1404: i = 10;break;
		case 0x1405: i = 11;break;
		case 0x1406: i = 12;break;
		case 0x1407: i = 13;break;
		case 0x1408: i = 14;break;
		case 0x1409: i = 15;break;
		case 0x140A: i = 16;break;
		case 0x140B: i = 17;break;
		case 0x140C: i = 18;break;
		case 0x1600: i = 19;break;
		case 0x1601: i = 20;break;
		case 0x1602: i = 21;break;
		case 0x1603: i = 22;break;
		case 0x1604: i = 23;break;
		case 0x1605: i = 24;break;
		case 0x1606: i = 25;break;
		case 0x1607: i = 26;break;
		case 0x1608: i = 27;break;
		case 0x1609: i = 28;break;
		case 0x160A: i = 29;break;
		case 0x160B: i = 30;break;
		case 0x160C: i = 31;break;
		case 0x1800: i = 32;break;
		case 0x1801: i = 33;break;
		case 0x1A00: i = 34;break;
		case 0x1A01: i = 35;break;
		case 0x2000: i = 36;break;
		case 0x2001: i = 37;break;
		case 0x2002: i = 38;break;
		case 0x2003: i = 39;break;
		case 0x2004: i = 40;break;
		case 0x2005: i = 41;break;
		case 0x2006: i = 42;break;
		case 0x2007: i = 43;break;
		case 0x2008: i = 44;break;
		case 0x2009: i = 45;break;
		case 0x200A: i = 46;break;
		case 0x200B: i = 47;break;
		case 0x200C: i = 48;break;
		case 0x200D: i = 49;break;
		case 0x200E: i = 50;break;
		case 0x200F: i = 51;break;
		case 0x2010: i = 52;break;
		case 0x2011: i = 53;break;
		case 0x2012: i = 54;break;
		case 0x2013: i = 55;break;
		case 0x2014: i = 56;break;
		case 0x2015: i = 57;break;
		case 0x2016: i = 58;break;
		case 0x2017: i = 59;break;
		case 0x2018: i = 60;break;
		case 0x2019: i = 61;break;
		case 0x201A: i = 62;break;
		case 0x201B: i = 63;break;
		case 0x201C: i = 64;break;
		case 0x201D: i = 65;break;
		case 0x201E: i = 66;break;
		case 0x201F: i = 67;break;
		case 0x2020: i = 68;break;
		case 0x2021: i = 69;break;
		case 0x2022: i = 70;break;
		case 0x2023: i = 71;break;
		case 0x2024: i = 72;break;
		case 0x2025: i = 73;break;
		case 0x2026: i = 74;break;
		case 0x2027: i = 75;break;
		case 0x2028: i = 76;break;
		case 0x2029: i = 77;break;
		case 0x202A: i = 78;break;
		case 0x202B: i = 79;break;
		case 0x202C: i = 80;break;
		case 0x202D: i = 81;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &CO_VehicleSBC_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status CO_VehicleSBC_PDO_status[2] = {s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index CO_VehicleSBC_firstIndex = {
  0, /* SDO_SVR */
  4, /* SDO_CLT */
  6, /* PDO_RCV */
  19, /* PDO_RCV_MAP */
  32, /* PDO_TRS */
  34 /* PDO_TRS_MAP */
};

const quick_index CO_VehicleSBC_lastIndex = {
  0, /* SDO_SVR */
  5, /* SDO_CLT */
  18, /* PDO_RCV */
  31, /* PDO_RCV_MAP */
  33, /* PDO_TRS */
  35 /* PDO_TRS_MAP */
};

const UNS16 CO_VehicleSBC_ObjdictSize = sizeof(CO_VehicleSBC_objdict)/sizeof(CO_VehicleSBC_objdict[0]); 

CO_Data CO_VehicleSBC_Data = CANOPEN_NODE_DATA_INITIALIZER(CO_VehicleSBC);

