
/* File generated by gen_cfile.py. Should not be modified. */

#include "CO_VehicleSBC.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS8 platformState = 0x0;		/* Mapped at index 0x2000, subindex 0x00 */
UNS16 SBCHeartbeat = 0x0;		/* Mapped at index 0x2001, subindex 0x00 */
UNS8 MotorControlState = 0x0;		/* Mapped at index 0x2002, subindex 0x00 */
UNS8 MotorEnableDisable = 0x0;		/* Mapped at index 0x2006, subindex 0x00 */
INTEGER32 MotorVelocityCommand = 0x0;		/* Mapped at index 0x2008, subindex 0x00 */
INTEGER32 MotorVelocityFeedback = 0x0;		/* Mapped at index 0x200E, subindex 0x00 */
INTEGER32 MotorCurrentFeedback = 0x0;		/* Mapped at index 0x2010, subindex 0x00 */
UNS16 BatteryVoltage = 0x0;		/* Mapped at index 0x2013, subindex 0x00 */
UNS8 MotorTemperature = 0x0;		/* Mapped at index 0x2019, subindex 0x00 */
UNS16 SoftwareMajorVersion = 0x0;		/* Mapped at index 0x2020, subindex 0x00 */
UNS16 SoftwareMinorVersion = 0x0;		/* Mapped at index 0x2021, subindex 0x00 */
UNS16 SoftwareMicroVersion = 0x0;		/* Mapped at index 0x2022, subindex 0x00 */
UNS16 SoftwareBuildVersion = 0x0;		/* Mapped at index 0x2023, subindex 0x00 */
UNS8 BootloaderMajorVersion = 0x0;		/* Mapped at index 0x2024, subindex 0x00 */
UNS8 BootloaderCommonVersion = 0x0;		/* Mapped at index 0x2025, subindex 0x00 */
UNS8 BootloaderMinorVersion = 0x0;		/* Mapped at index 0x2026, subindex 0x00 */
UNS8 BootloaderBuildVersion = 0x0;		/* Mapped at index 0x2027, subindex 0x00 */
UNS8 BITStatus = 0x0;		/* Mapped at index 0x2044, subindex 0x00 */
UNS8 platformStateStatus = 0x0;		/* Mapped at index 0x2051, subindex 0x00 */
UNS16 MotorControllerHeartbeat = 0x0;		/* Mapped at index 0x2060, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 CO_VehicleSBC_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 CO_VehicleSBC_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 CO_VehicleSBC_iam_a_slave = 0;

TIMER_HANDLE CO_VehicleSBC_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 CO_VehicleSBC_obj1000 = 0x0;	/* 0 */
                    subindex CO_VehicleSBC_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1000, NULL }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 CO_VehicleSBC_obj1001 = 0x0;	/* 0 */
                    subindex CO_VehicleSBC_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1001, NULL }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex CO_VehicleSBC_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1003, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1003[0], NULL }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 CO_VehicleSBC_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 CO_VehicleSBC_obj1006 = 0x0;   /* 0 */

/* index 0x100C :   Guard Time */ 
                    UNS16 CO_VehicleSBC_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 CO_VehicleSBC_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 CO_VehicleSBC_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1016 = 0;
                    UNS32 CO_VehicleSBC_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 CO_VehicleSBC_obj1017 = 0x3E8;	/* 1000 */
                    subindex CO_VehicleSBC_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1017, NULL }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 CO_VehicleSBC_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 CO_VehicleSBC_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 CO_VehicleSBC_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex CO_VehicleSBC_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1018, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1018_Vendor_ID, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1018_Product_Code, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1018_Revision_Number, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1018_Serial_Number, NULL }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x607;	/* 1543 */
                    UNS32 CO_VehicleSBC_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x587;	/* 1415 */
                    UNS8 CO_VehicleSBC_obj1280_Node_ID_of_the_SDO_Server = 0x7;	/* 7 */
                    subindex CO_VehicleSBC_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1280, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1280_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1280_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1280_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1281 :   Client SDO 2 Parameter. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1281 = 3; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1281_COB_ID_Client_to_Server_Transmit_SDO = 0x608;	/* 1544 */
                    UNS32 CO_VehicleSBC_obj1281_COB_ID_Server_to_Client_Receive_SDO = 0x588;	/* 1416 */
                    UNS8 CO_VehicleSBC_obj1281_Node_ID_of_the_SDO_Server = 0x8;	/* 8 */
                    subindex CO_VehicleSBC_Index1281[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1281, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1281_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1281_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1281_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1400_COB_ID_used_by_PDO = 0x287;	/* 647 */
                    UNS8 CO_VehicleSBC_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex CO_VehicleSBC_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1400, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1400_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1400_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1400_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1400_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1400_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1400_SYNC_start_value, NULL }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1401_COB_ID_used_by_PDO = 0x2C7;	/* 711 */
                    UNS8 CO_VehicleSBC_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex CO_VehicleSBC_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1401, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1401_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1401_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1401_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1401_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1401_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1401_SYNC_start_value, NULL }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1402_COB_ID_used_by_PDO = 0x2E7;	/* 743 */
                    UNS8 CO_VehicleSBC_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex CO_VehicleSBC_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1402, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1402_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1402_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1402_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1402_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1402_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1402_SYNC_start_value, NULL }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1403_COB_ID_used_by_PDO = 0x347;	/* 839 */
                    UNS8 CO_VehicleSBC_obj1403_Transmission_Type = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex CO_VehicleSBC_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1403, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1403_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1403_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1403_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1403_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1403_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1403_SYNC_start_value, NULL }
                     };

/* index 0x1404 :   Receive PDO 5 Parameter. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1404 = 6; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1404_COB_ID_used_by_PDO = 0x463;	/* 1123 */
                    UNS8 CO_VehicleSBC_obj1404_Transmission_Type = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj1404_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1404_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj1404_Event_Timer = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1404_SYNC_start_value = 0x0;	/* 0 */
                    subindex CO_VehicleSBC_Index1404[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1404, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1404_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1404_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1404_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1404_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1404_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1404_SYNC_start_value, NULL }
                     };

/* index 0x1405 :   Receive PDO 6 Parameter. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1405 = 6; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1405_COB_ID_used_by_PDO = 0x467;	/* 1127 */
                    UNS8 CO_VehicleSBC_obj1405_Transmission_Type = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj1405_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1405_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj1405_Event_Timer = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1405_SYNC_start_value = 0x0;	/* 0 */
                    subindex CO_VehicleSBC_Index1405[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1405, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1405_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1405_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1405_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1405_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1405_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1405_SYNC_start_value, NULL }
                     };

/* index 0x1406 :   Receive PDO 7 Parameter. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1406 = 6; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1406_COB_ID_used_by_PDO = 0x487;	/* 1159 */
                    UNS8 CO_VehicleSBC_obj1406_Transmission_Type = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj1406_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1406_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj1406_Event_Timer = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1406_SYNC_start_value = 0x0;	/* 0 */
                    subindex CO_VehicleSBC_Index1406[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1406, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1406_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1406_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1406_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1406_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1406_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1406_SYNC_start_value, NULL }
                     };

/* index 0x1407 :   Receive PDO 8 Parameter. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1407 = 6; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1407_COB_ID_used_by_PDO = 0x507;	/* 1287 */
                    UNS8 CO_VehicleSBC_obj1407_Transmission_Type = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj1407_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1407_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj1407_Event_Timer = 0x0;	/* 0 */
                    UNS8 CO_VehicleSBC_obj1407_SYNC_start_value = 0x0;	/* 0 */
                    subindex CO_VehicleSBC_Index1407[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1407, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1407_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1407_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1407_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1407_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1407_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1407_SYNC_start_value, NULL }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1600 = 1; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1600[] = 
                    {
                      0x20020008	/* 537001992 */
                    };
                    subindex CO_VehicleSBC_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1600, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1600[0], NULL }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1601 = 1; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1601[] = 
                    {
                      0x200E0020	/* 537788448 */
                    };
                    subindex CO_VehicleSBC_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1601, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1601[0], NULL }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1602 = 3; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1602[] = 
                    {
                      0x20100020,	/* 537919520 */
                      0x20130010,	/* 538116112 */
                      0x20190008	/* 538509320 */
                    };
                    subindex CO_VehicleSBC_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1602, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1602[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1602[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1602[2], NULL }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1603 = 1; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1603[] = 
                    {
                      0x20440008	/* 541327368 */
                    };
                    subindex CO_VehicleSBC_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1603, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1603[0], NULL }
                     };

/* index 0x1604 :   Receive PDO 5 Mapping. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1604 = 1; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1604[] = 
                    {
                      0x20510008	/* 542179336 */
                    };
                    subindex CO_VehicleSBC_Index1604[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1604, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1604[0], NULL }
                     };

/* index 0x1605 :   Receive PDO 6 Mapping. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1605 = 4; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1605[] = 
                    {
                      0x20200010,	/* 538968080 */
                      0x20210010,	/* 539033616 */
                      0x20220010,	/* 539099152 */
                      0x20230010	/* 539164688 */
                    };
                    subindex CO_VehicleSBC_Index1605[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1605, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1605[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1605[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1605[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1605[3], NULL }
                     };

/* index 0x1606 :   Receive PDO 7 Mapping. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1606 = 1; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1606[] = 
                    {
                      0x20600010	/* 543162384 */
                    };
                    subindex CO_VehicleSBC_Index1606[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1606, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1606[0], NULL }
                     };

/* index 0x1607 :   Receive PDO 8 Mapping. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1607 = 4; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1607[] = 
                    {
                      0x20240008,	/* 539230216 */
                      0x20250008,	/* 539295752 */
                      0x20260008,	/* 539361288 */
                      0x0	/* 0 */
                    };
                    subindex CO_VehicleSBC_Index1607[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1607, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1607[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1607[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1607[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1607[3], NULL }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1800 = 5; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1800_COB_ID_used_by_PDO = 0x185;	/* 389 */
                    UNS8 CO_VehicleSBC_obj1800_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 CO_VehicleSBC_obj1800_Inhibit_Time = 0x64;	/* 100 */
                    UNS8 CO_VehicleSBC_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj1800_Event_Timer = 0xA;	/* 10 */
                    subindex CO_VehicleSBC_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1800, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1800_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1800_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1800_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1800_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1800_Event_Timer, NULL }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1801 = 5; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1801_COB_ID_used_by_PDO = 0x187;	/* 391 */
                    UNS8 CO_VehicleSBC_obj1801_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 CO_VehicleSBC_obj1801_Inhibit_Time = 0x64;	/* 100 */
                    UNS8 CO_VehicleSBC_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj1801_Event_Timer = 0xA;	/* 10 */
                    subindex CO_VehicleSBC_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1801, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1801_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1801_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1801_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1801_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1801_Event_Timer, NULL }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1802 = 5; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1802_COB_ID_used_by_PDO = 0x2A7;	/* 679 */
                    UNS8 CO_VehicleSBC_obj1802_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 CO_VehicleSBC_obj1802_Inhibit_Time = 0x64;	/* 100 */
                    UNS8 CO_VehicleSBC_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CO_VehicleSBC_obj1802_Event_Timer = 0xA;	/* 10 */
                    subindex CO_VehicleSBC_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1802, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1802_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1802_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1802_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_obj1802_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&CO_VehicleSBC_obj1802_Event_Timer, NULL }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1A00 = 1; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1A00[] = 
                    {
                      0x20000008	/* 536870920 */
                    };
                    subindex CO_VehicleSBC_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1A00, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1A00[0], NULL }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1A01 = 1; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1A01[] = 
                    {
                      0x20010010	/* 536936464 */
                    };
                    subindex CO_VehicleSBC_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1A01, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1A01[0], NULL }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 CO_VehicleSBC_highestSubIndex_obj1A02 = 2; /* number of subindex - 1*/
                    UNS32 CO_VehicleSBC_obj1A02[] = 
                    {
                      0x20060008,	/* 537264136 */
                      0x20080020	/* 537395232 */
                    };
                    subindex CO_VehicleSBC_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CO_VehicleSBC_highestSubIndex_obj1A02, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1A02[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_VehicleSBC_obj1A02[1], NULL }
                     };

/* index 0x2000 :   Mapped variable platformState */
                    subindex CO_VehicleSBC_Index2000[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&platformState, NULL }
                     };

/* index 0x2001 :   Mapped variable SBCHeartbeat */
                    subindex CO_VehicleSBC_Index2001[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&SBCHeartbeat, NULL }
                     };

/* index 0x2002 :   Mapped variable MotorControlState */
                    subindex CO_VehicleSBC_Index2002[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MotorControlState, NULL }
                     };

/* index 0x2006 :   Mapped variable MotorEnableDisable */
                    subindex CO_VehicleSBC_Index2006[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MotorEnableDisable, NULL }
                     };

/* index 0x2008 :   Mapped variable MotorVelocityCommand */
                    subindex CO_VehicleSBC_Index2008[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&MotorVelocityCommand, NULL }
                     };

/* index 0x200E :   Mapped variable MotorVelocityFeedback */
                    subindex CO_VehicleSBC_Index200E[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&MotorVelocityFeedback, NULL }
                     };

/* index 0x2010 :   Mapped variable MotorCurrentFeedback */
                    subindex CO_VehicleSBC_Index2010[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&MotorCurrentFeedback, NULL }
                     };

/* index 0x2013 :   Mapped variable BatteryVoltage */
                    subindex CO_VehicleSBC_Index2013[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&BatteryVoltage, NULL }
                     };

/* index 0x2019 :   Mapped variable MotorTemperature */
                    subindex CO_VehicleSBC_Index2019[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MotorTemperature, NULL }
                     };

/* index 0x2020 :   Mapped variable SoftwareMajorVersion */
                    subindex CO_VehicleSBC_Index2020[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&SoftwareMajorVersion, NULL }
                     };

/* index 0x2021 :   Mapped variable SoftwareMinorVersion */
                    subindex CO_VehicleSBC_Index2021[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&SoftwareMinorVersion, NULL }
                     };

/* index 0x2022 :   Mapped variable SoftwareMicroVersion */
                    subindex CO_VehicleSBC_Index2022[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&SoftwareMicroVersion, NULL }
                     };

/* index 0x2023 :   Mapped variable SoftwareBuildVersion */
                    subindex CO_VehicleSBC_Index2023[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&SoftwareBuildVersion, NULL }
                     };

/* index 0x2024 :   Mapped variable BootloaderMajorVersion */
                    subindex CO_VehicleSBC_Index2024[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&BootloaderMajorVersion, NULL }
                     };

/* index 0x2025 :   Mapped variable BootloaderCommonVersion */
                    subindex CO_VehicleSBC_Index2025[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&BootloaderCommonVersion, NULL }
                     };

/* index 0x2026 :   Mapped variable BootloaderMinorVersion */
                    subindex CO_VehicleSBC_Index2026[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&BootloaderMinorVersion, NULL }
                     };

/* index 0x2027 :   Mapped variable BootloaderBuildVersion */
                    subindex CO_VehicleSBC_Index2027[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&BootloaderBuildVersion, NULL }
                     };

/* index 0x2044 :   Mapped variable BITStatus */
                    subindex CO_VehicleSBC_Index2044[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&BITStatus, NULL }
                     };

/* index 0x2051 :   Mapped variable platformStateStatus */
                    subindex CO_VehicleSBC_Index2051[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&platformStateStatus, NULL }
                     };

/* index 0x2060 :   Mapped variable MotorControllerHeartbeat */
                    subindex CO_VehicleSBC_Index2060[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&MotorControllerHeartbeat, NULL }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable CO_VehicleSBC_objdict[] = 
{
  { (subindex*)CO_VehicleSBC_Index1000,sizeof(CO_VehicleSBC_Index1000)/sizeof(CO_VehicleSBC_Index1000[0]), 0x1000},
  { (subindex*)CO_VehicleSBC_Index1001,sizeof(CO_VehicleSBC_Index1001)/sizeof(CO_VehicleSBC_Index1001[0]), 0x1001},
  { (subindex*)CO_VehicleSBC_Index1017,sizeof(CO_VehicleSBC_Index1017)/sizeof(CO_VehicleSBC_Index1017[0]), 0x1017},
  { (subindex*)CO_VehicleSBC_Index1018,sizeof(CO_VehicleSBC_Index1018)/sizeof(CO_VehicleSBC_Index1018[0]), 0x1018},
  { (subindex*)CO_VehicleSBC_Index1280,sizeof(CO_VehicleSBC_Index1280)/sizeof(CO_VehicleSBC_Index1280[0]), 0x1280},
  { (subindex*)CO_VehicleSBC_Index1281,sizeof(CO_VehicleSBC_Index1281)/sizeof(CO_VehicleSBC_Index1281[0]), 0x1281},
  { (subindex*)CO_VehicleSBC_Index1400,sizeof(CO_VehicleSBC_Index1400)/sizeof(CO_VehicleSBC_Index1400[0]), 0x1400},
  { (subindex*)CO_VehicleSBC_Index1401,sizeof(CO_VehicleSBC_Index1401)/sizeof(CO_VehicleSBC_Index1401[0]), 0x1401},
  { (subindex*)CO_VehicleSBC_Index1402,sizeof(CO_VehicleSBC_Index1402)/sizeof(CO_VehicleSBC_Index1402[0]), 0x1402},
  { (subindex*)CO_VehicleSBC_Index1403,sizeof(CO_VehicleSBC_Index1403)/sizeof(CO_VehicleSBC_Index1403[0]), 0x1403},
  { (subindex*)CO_VehicleSBC_Index1404,sizeof(CO_VehicleSBC_Index1404)/sizeof(CO_VehicleSBC_Index1404[0]), 0x1404},
  { (subindex*)CO_VehicleSBC_Index1405,sizeof(CO_VehicleSBC_Index1405)/sizeof(CO_VehicleSBC_Index1405[0]), 0x1405},
  { (subindex*)CO_VehicleSBC_Index1406,sizeof(CO_VehicleSBC_Index1406)/sizeof(CO_VehicleSBC_Index1406[0]), 0x1406},
  { (subindex*)CO_VehicleSBC_Index1407,sizeof(CO_VehicleSBC_Index1407)/sizeof(CO_VehicleSBC_Index1407[0]), 0x1407},
  { (subindex*)CO_VehicleSBC_Index1600,sizeof(CO_VehicleSBC_Index1600)/sizeof(CO_VehicleSBC_Index1600[0]), 0x1600},
  { (subindex*)CO_VehicleSBC_Index1601,sizeof(CO_VehicleSBC_Index1601)/sizeof(CO_VehicleSBC_Index1601[0]), 0x1601},
  { (subindex*)CO_VehicleSBC_Index1602,sizeof(CO_VehicleSBC_Index1602)/sizeof(CO_VehicleSBC_Index1602[0]), 0x1602},
  { (subindex*)CO_VehicleSBC_Index1603,sizeof(CO_VehicleSBC_Index1603)/sizeof(CO_VehicleSBC_Index1603[0]), 0x1603},
  { (subindex*)CO_VehicleSBC_Index1604,sizeof(CO_VehicleSBC_Index1604)/sizeof(CO_VehicleSBC_Index1604[0]), 0x1604},
  { (subindex*)CO_VehicleSBC_Index1605,sizeof(CO_VehicleSBC_Index1605)/sizeof(CO_VehicleSBC_Index1605[0]), 0x1605},
  { (subindex*)CO_VehicleSBC_Index1606,sizeof(CO_VehicleSBC_Index1606)/sizeof(CO_VehicleSBC_Index1606[0]), 0x1606},
  { (subindex*)CO_VehicleSBC_Index1607,sizeof(CO_VehicleSBC_Index1607)/sizeof(CO_VehicleSBC_Index1607[0]), 0x1607},
  { (subindex*)CO_VehicleSBC_Index1800,sizeof(CO_VehicleSBC_Index1800)/sizeof(CO_VehicleSBC_Index1800[0]), 0x1800},
  { (subindex*)CO_VehicleSBC_Index1801,sizeof(CO_VehicleSBC_Index1801)/sizeof(CO_VehicleSBC_Index1801[0]), 0x1801},
  { (subindex*)CO_VehicleSBC_Index1802,sizeof(CO_VehicleSBC_Index1802)/sizeof(CO_VehicleSBC_Index1802[0]), 0x1802},
  { (subindex*)CO_VehicleSBC_Index1A00,sizeof(CO_VehicleSBC_Index1A00)/sizeof(CO_VehicleSBC_Index1A00[0]), 0x1A00},
  { (subindex*)CO_VehicleSBC_Index1A01,sizeof(CO_VehicleSBC_Index1A01)/sizeof(CO_VehicleSBC_Index1A01[0]), 0x1A01},
  { (subindex*)CO_VehicleSBC_Index1A02,sizeof(CO_VehicleSBC_Index1A02)/sizeof(CO_VehicleSBC_Index1A02[0]), 0x1A02},
  { (subindex*)CO_VehicleSBC_Index2000,sizeof(CO_VehicleSBC_Index2000)/sizeof(CO_VehicleSBC_Index2000[0]), 0x2000},
  { (subindex*)CO_VehicleSBC_Index2001,sizeof(CO_VehicleSBC_Index2001)/sizeof(CO_VehicleSBC_Index2001[0]), 0x2001},
  { (subindex*)CO_VehicleSBC_Index2002,sizeof(CO_VehicleSBC_Index2002)/sizeof(CO_VehicleSBC_Index2002[0]), 0x2002},
  { (subindex*)CO_VehicleSBC_Index2006,sizeof(CO_VehicleSBC_Index2006)/sizeof(CO_VehicleSBC_Index2006[0]), 0x2006},
  { (subindex*)CO_VehicleSBC_Index2008,sizeof(CO_VehicleSBC_Index2008)/sizeof(CO_VehicleSBC_Index2008[0]), 0x2008},
  { (subindex*)CO_VehicleSBC_Index200E,sizeof(CO_VehicleSBC_Index200E)/sizeof(CO_VehicleSBC_Index200E[0]), 0x200E},
  { (subindex*)CO_VehicleSBC_Index2010,sizeof(CO_VehicleSBC_Index2010)/sizeof(CO_VehicleSBC_Index2010[0]), 0x2010},
  { (subindex*)CO_VehicleSBC_Index2013,sizeof(CO_VehicleSBC_Index2013)/sizeof(CO_VehicleSBC_Index2013[0]), 0x2013},
  { (subindex*)CO_VehicleSBC_Index2019,sizeof(CO_VehicleSBC_Index2019)/sizeof(CO_VehicleSBC_Index2019[0]), 0x2019},
  { (subindex*)CO_VehicleSBC_Index2020,sizeof(CO_VehicleSBC_Index2020)/sizeof(CO_VehicleSBC_Index2020[0]), 0x2020},
  { (subindex*)CO_VehicleSBC_Index2021,sizeof(CO_VehicleSBC_Index2021)/sizeof(CO_VehicleSBC_Index2021[0]), 0x2021},
  { (subindex*)CO_VehicleSBC_Index2022,sizeof(CO_VehicleSBC_Index2022)/sizeof(CO_VehicleSBC_Index2022[0]), 0x2022},
  { (subindex*)CO_VehicleSBC_Index2023,sizeof(CO_VehicleSBC_Index2023)/sizeof(CO_VehicleSBC_Index2023[0]), 0x2023},
  { (subindex*)CO_VehicleSBC_Index2024,sizeof(CO_VehicleSBC_Index2024)/sizeof(CO_VehicleSBC_Index2024[0]), 0x2024},
  { (subindex*)CO_VehicleSBC_Index2025,sizeof(CO_VehicleSBC_Index2025)/sizeof(CO_VehicleSBC_Index2025[0]), 0x2025},
  { (subindex*)CO_VehicleSBC_Index2026,sizeof(CO_VehicleSBC_Index2026)/sizeof(CO_VehicleSBC_Index2026[0]), 0x2026},
  { (subindex*)CO_VehicleSBC_Index2027,sizeof(CO_VehicleSBC_Index2027)/sizeof(CO_VehicleSBC_Index2027[0]), 0x2027},
  { (subindex*)CO_VehicleSBC_Index2044,sizeof(CO_VehicleSBC_Index2044)/sizeof(CO_VehicleSBC_Index2044[0]), 0x2044},
  { (subindex*)CO_VehicleSBC_Index2051,sizeof(CO_VehicleSBC_Index2051)/sizeof(CO_VehicleSBC_Index2051[0]), 0x2051},
  { (subindex*)CO_VehicleSBC_Index2060,sizeof(CO_VehicleSBC_Index2060)/sizeof(CO_VehicleSBC_Index2060[0]), 0x2060},
};

const indextable * CO_VehicleSBC_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode)
{
	int i;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1017: i = 2;break;
		case 0x1018: i = 3;break;
		case 0x1280: i = 4;break;
		case 0x1281: i = 5;break;
		case 0x1400: i = 6;break;
		case 0x1401: i = 7;break;
		case 0x1402: i = 8;break;
		case 0x1403: i = 9;break;
		case 0x1404: i = 10;break;
		case 0x1405: i = 11;break;
		case 0x1406: i = 12;break;
		case 0x1407: i = 13;break;
		case 0x1600: i = 14;break;
		case 0x1601: i = 15;break;
		case 0x1602: i = 16;break;
		case 0x1603: i = 17;break;
		case 0x1604: i = 18;break;
		case 0x1605: i = 19;break;
		case 0x1606: i = 20;break;
		case 0x1607: i = 21;break;
		case 0x1800: i = 22;break;
		case 0x1801: i = 23;break;
		case 0x1802: i = 24;break;
		case 0x1A00: i = 25;break;
		case 0x1A01: i = 26;break;
		case 0x1A02: i = 27;break;
		case 0x2000: i = 28;break;
		case 0x2001: i = 29;break;
		case 0x2002: i = 30;break;
		case 0x2006: i = 31;break;
		case 0x2008: i = 32;break;
		case 0x200E: i = 33;break;
		case 0x2010: i = 34;break;
		case 0x2013: i = 35;break;
		case 0x2019: i = 36;break;
		case 0x2020: i = 37;break;
		case 0x2021: i = 38;break;
		case 0x2022: i = 39;break;
		case 0x2023: i = 40;break;
		case 0x2024: i = 41;break;
		case 0x2025: i = 42;break;
		case 0x2026: i = 43;break;
		case 0x2027: i = 44;break;
		case 0x2044: i = 45;break;
		case 0x2051: i = 46;break;
		case 0x2060: i = 47;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &CO_VehicleSBC_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status CO_VehicleSBC_PDO_status[3] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index CO_VehicleSBC_firstIndex = {
  0, /* SDO_SVR */
  4, /* SDO_CLT */
  6, /* PDO_RCV */
  14, /* PDO_RCV_MAP */
  22, /* PDO_TRS */
  25 /* PDO_TRS_MAP */
};

const quick_index CO_VehicleSBC_lastIndex = {
  0, /* SDO_SVR */
  5, /* SDO_CLT */
  13, /* PDO_RCV */
  21, /* PDO_RCV_MAP */
  24, /* PDO_TRS */
  27 /* PDO_TRS_MAP */
};

const UNS16 CO_VehicleSBC_ObjdictSize = sizeof(CO_VehicleSBC_objdict)/sizeof(CO_VehicleSBC_objdict[0]); 

CO_Data CO_VehicleSBC_Data = CANOPEN_NODE_DATA_INITIALIZER(CO_VehicleSBC);

